# Generated by Django 5.0.2 on 2024-03-01 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=15)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('min_students', models.IntegerField()),
                ('max_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('product_access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.access')),
            ],
        ),
    ]
